<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Dudlewebs\\WPMCS\\Symfony\\Polyfill\\Php81\\' => array($vendorDir . '/symfony/polyfill-php81'),
    'Dudlewebs\\WPMCS\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Dudlewebs\\WPMCS\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Dudlewebs\\WPMCS\\Rize\\' => array($vendorDir . '/rize/uri-template/src/Rize'),
    'Dudlewebs\\WPMCS\\Ramsey\\Uuid\\' => array($vendorDir . '/ramsey/uuid/src'),
    'Dudlewebs\\WPMCS\\Ramsey\\Collection\\' => array($vendorDir . '/ramsey/collection/src'),
    'Dudlewebs\\WPMCS\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Dudlewebs\\WPMCS\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Dudlewebs\\WPMCS\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Dudlewebs\\WPMCS\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Dudlewebs\\WPMCS\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Dudlewebs\\WPMCS\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Dudlewebs\\WPMCS\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Dudlewebs\\WPMCS\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Dudlewebs\\WPMCS\\Grpc\\Gcp\\' => array($vendorDir . '/google/grpc-gcp/src'),
    'Dudlewebs\\WPMCS\\Grpc\\' => array($vendorDir . '/grpc/grpc/src/lib'),
    'Dudlewebs\\WPMCS\\Google\\Type\\' => array($vendorDir . '/google/common-protos/src/Type'),
    'Dudlewebs\\WPMCS\\Google\\Rpc\\' => array($vendorDir . '/google/common-protos/src/Rpc'),
    'Dudlewebs\\WPMCS\\Google\\Protobuf\\' => array($vendorDir . '/google/protobuf/src/Google/Protobuf'),
    'Dudlewebs\\WPMCS\\Google\\LongRunning\\' => array($vendorDir . '/google/longrunning/src/LongRunning'),
    'Dudlewebs\\WPMCS\\Google\\Iam\\' => array($vendorDir . '/google/common-protos/src/Iam'),
    'Dudlewebs\\WPMCS\\Google\\Cloud\\Storage\\' => array($vendorDir . '/google/cloud-storage/src'),
    'Dudlewebs\\WPMCS\\Google\\Cloud\\Core\\' => array($vendorDir . '/google/cloud-core/src'),
    'Dudlewebs\\WPMCS\\Google\\Cloud\\' => array($vendorDir . '/google/common-protos/src/Cloud'),
    'Dudlewebs\\WPMCS\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Dudlewebs\\WPMCS\\Google\\Api\\' => array($vendorDir . '/google/common-protos/src/Api'),
    'Dudlewebs\\WPMCS\\Google\\ApiCore\\LongRunning\\' => array($vendorDir . '/google/longrunning/src/ApiCore/LongRunning'),
    'Dudlewebs\\WPMCS\\Google\\ApiCore\\' => array($vendorDir . '/google/gax/src'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Type\\' => array($vendorDir . '/google/common-protos/metadata/Type'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Rpc\\' => array($vendorDir . '/google/common-protos/metadata/Rpc'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Protobuf\\' => array($vendorDir . '/google/protobuf/src/GPBMetadata/Google/Protobuf'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Longrunning\\' => array($vendorDir . '/google/longrunning/metadata/Longrunning'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Logging\\' => array($vendorDir . '/google/common-protos/metadata/Logging'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Iam\\' => array($vendorDir . '/google/common-protos/metadata/Iam'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Cloud\\' => array($vendorDir . '/google/common-protos/metadata/Cloud'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\Google\\Api\\' => array($vendorDir . '/google/common-protos/metadata/Api'),
    'Dudlewebs\\WPMCS\\GPBMetadata\\ApiCore\\' => array($vendorDir . '/google/gax/metadata/ApiCore'),
    'Dudlewebs\\WPMCS\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Dudlewebs\\WPMCS\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
    'Dudlewebs\\WPMCS\\' => array($vendorDir . '/vendor'),
);
