<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/control.proto
namespace Dudlewebs\WPMCS\GPBMetadata\Google\Api;

class Control
{
    public static $is_initialized = \false;
    public static function initOnce()
    {
        $pool = \Dudlewebs\WPMCS\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == \true) {
            return;
        }
        \Dudlewebs\WPMCS\GPBMetadata\Google\Api\Policy::initOnce();
        $pool->internalAddGeneratedFile('
ñ
google/api/control.proto
google.api"Q
Control
environment (	1
method_policies (2.google.api.MethodPolicyBn
com.google.apiBControlProtoPZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig¢GAPIbproto3', \true);
        static::$is_initialized = \true;
    }
}
