<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/logging.proto
namespace Dudlewebs\WPMCS\GPBMetadata\Google\Api;

class Logging
{
    public static $is_initialized = \false;
    public static function initOnce()
    {
        $pool = \Dudlewebs\WPMCS\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == \true) {
            return;
        }
        $pool->internalAddGeneratedFile('
ø
google/api/logging.proto
google.api"×
LoggingE
producer_destinations (2&.google.api.Logging.LoggingDestinationE
consumer_destinations (2&.google.api.Logging.LoggingDestination>
LoggingDestination
monitored_resource (	
logs (	Bn
com.google.apiBLoggingProtoPZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig¢GAPIbproto3', \true);
        static::$is_initialized = \true;
    }
}
